- name: Hello World
  hosts: localhost
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: "Hello World"    
    - name: print new Hello World
      ansible.builtin.debug:
       msg: "This is Narendra"
    - name: print wife status
      ansible.builtin.debug:
       msg: "my wife is happy"
