- name: uninstll nginx
  hosts: frontend
  become: yes
  tasks:
   - name: remove nginx package
     ansible.builtin.package:
       name: nginx
       state: absent

   - name: print the message 
     ansible.builtin.dubug:
      msg: "nginix is uninsalled"