- name: install nginx
  hosts: frontend
  become: yes 
  tasks:
   - name: nginx package install
     ansible.builtin.package:
      name: nginx
      state: present

   - name: start nginx service
     ansible.builtin.service:
      name: nginx
      state: started

   - name: enble the nginx service
     ansible.builtin.service:
      name: nginx
      enable: yes

   - name : print the message
     ansible.builtin.debug:
      msg: "nginx is sucessfully enabled"
