- name: install nginx
  hosts: frontend
  become: yes
  tasks:
   - name: ensure install nginx
     ansible.builtin.package:
     name: niginx
     state: present

   - name: ensure nginx is started
     ansible.builtin.service:
     name: nginx
     state: started
 
   - name: ensure nginx is enabled
     ansible.builtin.service:
     name: nginx
     enabled: yes