- name: nginx install and run 
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx server
    ansible.builtin.package:
     name: nginx
     state: present

  - name: start nginx server 
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes

  - name: to print the message
    ansible.builtin.debug:
    msg: "we have installed and started and run the nginx service"
  