- name: nginx install and run 
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx server
    ansible.builtin.package:
     name: niginx
     state: present

  - name: start nginx server 
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes
 
  