- name: multi play
  hosts: local
  connection: local
  tasks:
   - name: print message play1
     ansible.builtin.debug:
      msg: "playing the team play1"

- name: multi play  
  become: yes
  hosts: frontend 
  tasks:
  - name: print message play2
    ansible.builtin.debug:
     msg: "playing the team play2"
