- name: print vars
  hosts: local
  connection: local
  vars:
   COURSE: ansible
   DURATION: 10hrs
   TRAINER: sivakumar
  tasks:
  - name: print the vars message
    ansible.builtin.debug:
     msg: "course is: {{COURSE}}, duration is: {{DURATION}}, trainer is: {{TRAINER}}"