- name: working with the variables
  hosts: frontend
  become: yes
  vars: 
   COURSE: ansible
   DURATION: 10hrs
   TRAINER: narendra
  tasks:
   - name: print the message
     ansible.builtin.debug:
      msg: "Hello, course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}"