- name: ansible data types
  hosts: local
  connection: local
  vars:
   DURATION: 120 hrs
   COURSE: "DevsecOps with AWS"
   IS_LIVE: true
   Tools:
   - Linux
   - Shell Scripting
   - ansible
   - docker
   - kubernetes
   CONCEPTS: 
    CI: jenkins
    SCRIPTING: "shell, Ansible, python"
  tasks:
  - name: print course information
    ansible.builtin.debug:
    msg: " course is: {{COURSE}}, durations is: {{DURATION}}, is live: {{IS_LIVE}}, tools are: {{Tools}}, concepts are: {{CONCEPTS}}""