- name: install nginx using facts
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx in RedHat
    ansible.builtin.dnf:
     name: nginx
     state: present
    when: ansible_os_family == "Redhat"

  - name: install nginx in Debian
    ansible.builtin.apt:
     name: nginx
     state: present
    when: ansible_os_family == "Debian"
    