- name: playbook control using ansible facts
  hosts: frontend
  become: yes
  tasks:
  - name: install nginix if os is RedHat
    ansible.builtin.dnf:
     name: nginx
     state: present
    when: ansible_os_family == "RedHat"

  - name: install nginx if os is Debian
    ansible.builtin.apt:
     name: nginx
     state: present 
    when: ansible_os_family == "Debian"