- name : install ngingx gathering facts
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx if os is redhat
    ansible.builtin.dnf:
     name: nginx
     state: present
    when: ansible_os_family == " RedHat "

  - name: install nginx if os is debian
    ansible.builtin.apt:
     name: nginx
     state: present
    when: ansible_os_family == " Debian "

  - name: start nginx service
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes
