- name: install and unisntall packages
  hosts: frontend
  become: yes
  tasks:
  - name: install and unisntall
    ansible.builtin.package:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
    loop:
    - { name: 'nginx', state: 'installed' } 
    - { name: 'httpd', state: 'uninstalled' }
    - { name: 'mysql', state: 'uninstalled' } 