- name: install packages
  hosts: frontend
  become: yes
  tasks:
  - name: install 
    ansible.builtin.package:
     name: "{{ item }}"
     state: installed
    loop:
    - nginx
    - httpd
    - mysql
    - zip
  - name: start nginx
    ansible.builtin.systemd:
     name: nginx
     state: started
     enabled: true  
  - name: start httpd 
    ansible.builtin.systemd:
     name: httpd
     state: started
     enabled: true
  - name: start httpd 
    ansible.builtin.systemd:
     name: mysql
     state: started
     enabled: true