- name: install packages
  hosts: frontend
  become: yes
  tasks:
  - name: install
    ansible.builtin.package:
     name: "{{ item }}"
     state: present
     loop:
     - nginx
     - httpd
     - mysql
     - zip
