- name: install packages
  hosts: frontend
  become: yes
  tasks:
  - name: install 
    ansible.builtin.package:
     name: "{{ item }}"
     state: installed
    loop:
    - nginx
    - httpd
    - mysql
    - zip
  -name: start
    ansible.builtin.service:
     name: "{{ item }}"
     state: started
     enabled:yes
    loop:
    - nginx
    - httpd
    - mysql