- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print the loops
    ansible.builtin.debug:
     msg: " Hello: {{ item }}"  # item is the reserved keyword in ansuble
    loop:
    - narendra
    - naresh
    - mukesh
    - suresh