- name: print loops
  hosts: local
  connection: local
  tasks:
   - name: print message 
     ansible.builtin.debug:
      msg: "Hello: {{item}}"
     loop:
     - naresh
     - suresh
     - mukesh
     - sukesh
     
