- name: install and uninstall
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
    loop:
    - { name: nginx, state: present }
    - { name: httpd, state: absent } 