- name: shell vs command
  hosts: frontend
  tasks:
  - name: redirect the output
    ansible.builtin.shell: " ls -ltr > /tmp/output.txt "
    register: command_result

  - name: print the output
    ansible.builtin.debug:
     msg: {{ mmand_result }}