- name: shell vs command
  hosts: frontend
  tasks:
  - name: redirect ls output to /tmp/ls.txt
    #ansible.builtin.shell: " ls -ltr > /tmp/ls.txt "
    ansible.builtin.command: " ls -ltr > /tmp/ls.txt "