- name: print the variables
  hosts: inventory.ini
  vars_prompt:
  - name: USERNAME
    prompt: enter the username
    private: true

  - name: PASSWORD
    prompt: enter the password
    private: true
  
  tasks:
  - name: printer the user information
    ansible.builtin.debug:
     msg: "Hello world: enter username {{ USERNAME }}, enter password {{ PASSWORD }}"
