- name: print the vars in file
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print the message
    ansible.builtin.debug:
     msg: "course is: {{COURSE}}, duration is: {{DURATION}}, trainer is: {{TRAINER}}"