- name: print the vars_prompt
  hosts: local
  connection: local
  vars_prompt:
   - name: USERNAME
     prompt: "enter username"
     private: true

   - name: PASSWORD
     prompt: "enter password"
     private: false
     
  tasks:
  - name: enter the username and password
    ansible.builtin.debug:
     msg: "username is: {{USERNAME}}, password is: {{PASSWORD}}"
