- name: print the variables
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print the messages
    ansible.builtin.debug:
     msg: "Hello,course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}"