- name: print the variables
  hosts: local
  connection: local
  vars_prompt:
  - name: USERNAME
    prompt: enter the username
    proivate: true
    
  - name: PASSWORD
    prompt: enter the passwordt
    private: true
  
  tasks:
  - name: printer the user information
    ansible.builtin.debug:
     msg: "Hello world: enter username {{ USERNAME }}, enter password {{ PASSWORD }}"
